from langchain_ollama import ChatOllama
from langchain.agents import create_agent
from rich.console import Console
from rich.panel import Panel
from rich.markdown import Markdown
import datetime

console = Console()

REPORTER_PROMPT = """You are an expert cybersecurity report writer. 
Create a clean, professional, and actionable security audit report.

Use this exact structure:

# 🔐 DroidTown Security Audit Report

**Generated on:** {timestamp}  
**Total Files Scanned:** {file_count}

## 📊 Executive Summary
- **Overall Risk Level:** [CRITICAL / HIGH / MEDIUM / LOW]
- **Total Issues:** X  
- Critical: X | High: X | Medium: X | Low: X

## 🔍 Detailed Findings
{paste_all_file_findings}

## ✅ Recommendations
Provide clear, prioritized recommendations based on the findings.

**Report generated by DroidTown Security Agent using GLM-5.1**"""

llm = ChatOllama(model="glm-5.1:cloud", temperature=0.0)

reporter_agent = create_agent(
    model=llm,
    tools=[],
    system_prompt=REPORTER_PROMPT
)

def generate_professional_report(findings_list: list):
    """findings_list = [{"file": str, "findings": str}, ...]"""
    timestamp = datetime.datetime.now().strftime("%B %d, %Y at %H:%M:%S")
    file_count = len(findings_list)

    raw_findings = "\n\n".join(
        f"### 📄 {item['file']}\n{item['findings']}" for item in findings_list
    )

    input_text = f"""Generate the full professional report:

Files scanned: {file_count}
Timestamp: {timestamp}

Raw findings from all files:
{raw_findings}
"""

    result = reporter_agent.invoke({
        "messages": [{"role": "user", "content": input_text}]
    })

    report = result["messages"][-1].content if isinstance(result, dict) and "messages" in result else str(result)

    # Display beautiful colored report in terminal
    console.print(Panel(Markdown(report), title="🔐 DroidTown Security Report", border_style="bold blue", padding=(1, 2)))

    # Save markdown version
    with open("security-report.md", "w", encoding="utf-8") as f:
        f.write(report)

    console.print(f"\n💾 Report saved as [bold green]security-report.md[/bold green]")
    return report
